### ISSUE TITLE
Homeassistant ability to run arbitrary `on_press` actions

### ISSUE THREAD

**Issue by mcristina422** [LocalBytes/localdeck-config#44]
Having the ability to write/save YAML in the Configurator, linked to a button press for custom actions would be really nice. I've been manually modifying the YAML myself, but maintaining this becomes painful. 

While the Configurator could directly support these actions in the UI in the future, this helps rapid prototype things now while those get implemented.

For example, I want a button press to increase/decrease the brightness of the a light. 
```yaml
  - platform: matrix_keypad
    id: keypad_button_13
    name: Button 13
    internal: false
    keypad_id: keypad
    key: M
    on_press:
      - homeassistant.service:
          service: light.turn_on
          data: 
            entity_id: light.corner_lamp
            brightness_step_pct: '10'
  - platform: matrix_keypad
    id: keypad_button_07
    name: Button 07
    internal: false
    keypad_id: keypad
    key: G
    on_press:
      - homeassistant.service:
          service: light.turn_on
          data: 
            entity_id: light.corner_lamp
            brightness_step_pct: '-10'
```

I think having the configurator accept the `on_press` YAML directly would allow loads of new things to be tested easily.
